version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
        reservations:
          cpus: '1.0'
          memory: 200M
    ports:
      - "5432:5432"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
     - DATABSE_HOST=127.0.0.1
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=root

  pgadmin:
   image: dpage/pgadmin4
   environment:
    PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
    PGADMIN_DEFAULT_PASSWORD: "admin"
   ports:
    - "80:80"
   depends_on:
    - postgres